[package]
name = "jam-primitives"
version = "0.1.0"
edition = "2024"
description = "JAM protocol primitives"
license = "Apache-2.0"

[dependencies]
blake3.workspace = true
ed25519-dalek = { workspace = true, features = ["rand_core"] }
